language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: FORK_BRANCH=no_camlp4 FORK_USER=ygrek bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - osx
  - linux
