lib: [
  "_build/install/default/lib/devkit/META" {"META"}
  "_build/install/default/lib/devkit/devkit.a" {"devkit.a"}
  "_build/install/default/lib/devkit/devkit.cma" {"devkit.cma"}
  "_build/install/default/lib/devkit/devkit.cmi" {"devkit.cmi"}
  "_build/install/default/lib/devkit/devkit.cmt" {"devkit.cmt"}
  "_build/install/default/lib/devkit/devkit.cmx" {"devkit.cmx"}
  "_build/install/default/lib/devkit/devkit.cmxa" {"devkit.cmxa"}
  "_build/install/default/lib/devkit/devkit.cmxs" {"devkit.cmxs"}
  "_build/install/default/lib/devkit/devkit.dune" {"devkit.dune"}
  "_build/install/default/lib/devkit/devkit.ml" {"devkit.ml"}
  "_build/install/default/lib/devkit/opam" {"opam"}
]
doc: [
  "_build/install/default/doc/devkit/README"
]
