name: devkit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        ocaml-version:
          - 4.14
          - 5.1

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update apt
      run: sudo apt-get update

    - name: Set up OCaml ${{ matrix.ocaml-version }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
        dune-cache: true
        opam-depext-flags: "--with-test"
        allow-prerelease-opam: true

    - name: Install OCaml deps
      run: opam install . --deps-only --with-test
      
    - name: Build
      run: opam exec -- dune build --profile=release

    - name: Test
      run: opam exec -- dune runtest --profile=release
